---
title: "outputs"
author: "Jonna Teinonen"
date: '2023-05-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# PART 1: Calculating the Pooled Parameters for Robust Methods

## 1.1 Robust Methods

```{r}
sample_sizes <-  c(50, 100, 200, 500, 1000)   # Sample sizes
response_rates <- c(60, 70,  80)              # Response rates
scenarios <- c(1, 2, 3, 4, 5)                 # Model scenario

# Looping the result files created in R script "simulation_code_main" for 
# robust methods 
for(s in scenarios){
  for (ss in sample_sizes){
    for (rr in response_rates){
      
      # # Path where the result files for the robust methods are located
        file_name <- paste0("C:..\\robust\\results\\simulation_rr", rr, "_n", ss, "_s", s, "_robust.RData")
        load(file_name)
  
      }
    }
  }
 
```


```{r}
# List of the wanted parameters: 
# scenario, response rate, sample size
param_list <- list(
  list(1, 60, 50      ) ,
  list(1, 70, 50      ) ,
  list(1, 80, 50      ) ,
  list(1, 60, 100     ) ,
  list(1, 70, 100     ) ,
  list(1, 80, 100     ) ,
  list(1, 60, 200     ) ,
  list(1, 70, 200     ) ,
  list(1, 80, 200     ) ,
  list(1, 60, 500     ) ,
  list(1, 70, 500     ) ,
  list(1, 80, 500     ) ,
  list(1, 60, 1000    ) ,
  list(1, 70, 1000    ) ,
  list(1, 80, 1000    ) ,
  list(2, 60, 50      ) ,
  list(2, 70, 50      ) ,
  list(2, 80, 50      ) ,
  list(2, 60, 100     ) ,
  list(2, 70, 100     ) ,
  list(2, 80, 100     ) ,
  list(2, 60, 200     ) ,
  list(2, 70, 200     ) ,
  list(2, 80, 200     ) ,
  list(2, 60, 500     ) ,
  list(2, 70, 500     ) ,
  list(2, 80, 500     ) ,
  list(2, 60, 1000    ) ,
  list(2, 70, 1000    ) ,
  list(2, 80, 1000    ) ,
  list(3, 60, 50      ) ,
  list(3, 70, 50      ) ,
  list(3, 80, 50      ) ,
  list(3, 60, 100     ) ,
  list(3, 70, 100     ) ,
  list(3, 80, 100     ) ,
  list(3, 60, 200     ) ,
  list(3, 70, 200     ) ,
  list(3, 80, 200     ) ,
  list(3, 60, 500     ) ,
  list(3, 70, 500     ) ,
  list(3, 80, 500     ) ,
  list(3, 60, 1000    ) ,
  list(3, 70, 1000    ) ,
  list(3, 80, 1000    ) ,
  list(4, 60, 50      ) ,
  list(4, 70, 50      ) ,
  list(4, 80, 50      ) ,
  list(4, 60, 100     ) ,
  list(4, 70, 100     ) ,
  list(4, 80, 100     ) ,
  list(4, 60, 200     ) ,
  list(4, 70, 200     ) ,
  list(4, 80, 200     ) ,
  list(4, 60, 500     ) ,
  list(4, 70, 500     ) ,
  list(4, 80, 500     ) ,
  list(4, 60, 1000    ) ,
  list(4, 70, 1000    ) ,
  list(4, 80, 1000    ) ,
  list(5, 60, 50      ) ,
  list(5, 70, 50      ) ,
  list(5, 80, 50      ) ,
  list(5, 60, 100     ) ,
  list(5, 70, 100     ) ,
  list(5, 80, 100     ) ,
  list(5, 60, 200     ) ,
  list(5, 70, 200     ) ,
  list(5, 80, 200     ) ,
  list(5, 60, 500     ) ,
  list(5, 70, 500     ) ,
  list(5, 80, 500     ) ,
  list(5, 60, 1000    ) ,
  list(5, 70, 1000    ) ,
  list(5, 80, 1000    )
)
```

```{r}
# Names of the loaded result files
result_list <- list(
  simulation_rr60_n50_s1_robust,
  simulation_rr70_n50_s1_robust,
  simulation_rr80_n50_s1_robust,
  simulation_rr60_n100_s1_robust,
  simulation_rr70_n100_s1_robust,
  simulation_rr80_n100_s1_robust,
  simulation_rr60_n200_s1_robust,
  simulation_rr70_n200_s1_robust,
  simulation_rr80_n200_s1_robust,
  simulation_rr60_n500_s1_robust,
  simulation_rr70_n500_s1_robust,
  simulation_rr80_n500_s1_robust,
  simulation_rr60_n1000_s1_robust,
  simulation_rr70_n1000_s1_robust,
  simulation_rr80_n1000_s1_robust,
  simulation_rr60_n50_s2_robust,
  simulation_rr70_n50_s2_robust,
  simulation_rr80_n50_s2_robust,
  simulation_rr60_n100_s2_robust,
  simulation_rr70_n100_s2_robust,
  simulation_rr80_n100_s2_robust,
  simulation_rr60_n200_s2_robust,
  simulation_rr70_n200_s2_robust,
  simulation_rr80_n200_s2_robust,
  simulation_rr60_n500_s2_robust,
  simulation_rr70_n500_s2_robust,
  simulation_rr80_n500_s2_robust,
  simulation_rr60_n1000_s2_robust,
  simulation_rr70_n1000_s2_robust,
  simulation_rr80_n1000_s2_robust,
  simulation_rr60_n50_s3_robust,
  simulation_rr70_n50_s3_robust,
  simulation_rr80_n50_s3_robust,
  simulation_rr60_n100_s3_robust,
  simulation_rr70_n100_s3_robust,
  simulation_rr80_n100_s3_robust,
  simulation_rr60_n200_s3_robust,
  simulation_rr70_n200_s3_robust,
  simulation_rr80_n200_s3_robust,
  simulation_rr60_n500_s3_robust,
  simulation_rr70_n500_s3_robust,
  simulation_rr80_n500_s3_robust,
  simulation_rr60_n1000_s3_robust,
  simulation_rr70_n1000_s3_robust,
  simulation_rr80_n1000_s3_robust,
  simulation_rr60_n50_s4_robust,
  simulation_rr70_n50_s4_robust,
  simulation_rr80_n50_s4_robust,
  simulation_rr60_n100_s4_robust,
  simulation_rr70_n100_s4_robust,
  simulation_rr80_n100_s4_robust,
  simulation_rr60_n200_s4_robust,
  simulation_rr70_n200_s4_robust,
  simulation_rr80_n200_s4_robust,
  simulation_rr60_n500_s4_robust,
  simulation_rr70_n500_s4_robust,
  simulation_rr80_n500_s4_robust,
  simulation_rr60_n1000_s4_robust,
  simulation_rr70_n1000_s4_robust,
  simulation_rr80_n1000_s4_robust,
  simulation_rr60_n50_s5_robust,
  simulation_rr70_n50_s5_robust,
  simulation_rr80_n50_s5_robust,
  simulation_rr60_n100_s5_robust,
  simulation_rr70_n100_s5_robust,
  simulation_rr80_n100_s5_robust,
  simulation_rr60_n200_s5_robust,
  simulation_rr70_n200_s5_robust,
  simulation_rr80_n200_s5_robust,
  simulation_rr60_n500_s5_robust,
  simulation_rr70_n500_s5_robust,
  simulation_rr80_n500_s5_robust,
  simulation_rr60_n1000_s5_robust,
  simulation_rr70_n1000_s5_robust,
  simulation_rr80_n1000_s5_robust
)
```


```{r}
# Looping each robust result file
for (idx in 1:length(result_list)){
  
  PP_results <- result_list[[idx]]
  s  <- param_list[[idx]][[1]]
  rr <- param_list[[idx]][[2]]
  n  <- param_list[[idx]][[3]]
  
  # List of the results for each category of Y
  Yc1_APP_data <- list()
  Yc2_APP_data <- list()
  Yc3_APP_data <- list()
  combined_data <- list()
  
  # Looping the results of each method
  for (i in 1:length(PP_results)){
    
    # Binds the results of the same method during different iterations 
    # into a same data frame
    binded_data <- do.call(rbind, PP_results[[i]])
  
    # Calculating pooled parameters: MEP, MSE, SD and CR for each 
    # category of Y
    Yc1_APP_data[[i]] <- c(colMeans(binded_data[binded_data$var == 1, c(1, 2)]),
                           sd(binded_data[binded_data$var == 1, 1]),
                           mean(binded_data[binded_data$var == 1, 5]))
    names(Yc1_APP_data[[i]]) <- c("Est", "SE", "SD", "CR")
    
    
    Yc2_APP_data[[i]] <- c(colMeans(binded_data[binded_data$var == 2, c(1, 2)]),
                           sd(binded_data[binded_data$var == 2, 1]),
                           mean(binded_data[binded_data$var == 2, 5]))
    
    names(Yc2_APP_data[[i]]) <- c("Est", "SE", "SD", "CR")
    
    Yc3_APP_data[[i]] <- c(colMeans(binded_data[binded_data$var == 3, c(1, 2)]),
                           sd(binded_data[binded_data$var == 3, 1]),
                           mean(binded_data[binded_data$var == 3, 5]))
    
    names(Yc3_APP_data[[i]]) <- c("Est", "SE", "SD", "CR")
    
    combined_data[[i]] <- binded_data  # Saves the binded data
    combined_data[[i]]$method <- i     # Saves the method as a number
  
  }
  
    # Adding the method numbers and categories of Y
    # NOTE:
    # 1 = MRIC R2 MF
    # 2 = MRIC R2 MF
    # 3 = MRIC R2 CS
    # 4 = MRIC R2 N
    # 5 = MRIC AIC
    # 6 = MRIC HL
    # 7 = MRNNMI
    # 8 = DRNNMI
    # 9 = MRPMMI
    Yc1_APP_data2 <- as.data.frame(do.call(rbind,Yc1_APP_data))
    Yc1_APP_data2$method <- c(1, 2, 3, 4, 5, 6, 7, 8, 9) # MI method 
    Yc1_APP_data2$level <- 1 # Category of Y
    
    Yc2_APP_data2 <- as.data.frame(do.call(rbind,Yc2_APP_data))
    Yc2_APP_data2$method <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
    Yc2_APP_data2$level <- 2
    
    Yc3_APP_data2 <- as.data.frame(do.call(rbind,Yc3_APP_data))
    Yc3_APP_data2$method <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
    Yc3_APP_data2$level <- 3 
    
    # Combining all pooled parameters into one dataframe for tables and figures
    pooled_param_data_all_temp <- do.call(rbind, list(Yc1_APP_data2, 
                                                      Yc2_APP_data2, 
                                                      Yc3_APP_data2))
    
    # Adding sample size, response rate and working scenario number
    pooled_param_data_all_temp$n <- n
    pooled_param_data_all_temp$RR <- rr
    pooled_param_data_all_temp$scenario <- s
    pooled_param_data_all_temp

    # Saving the dataset
    file_name <- paste0("C:\\...\\robust\\pooled_robust_results_rr", rr, "_n", n, "_s", s, ".rds")
      
    saveRDS(pooled_param_data_all_temp, file = file_name)
    
    # Saving the combined datasets into one dataframe (used for figures)
    combined_data_all_temp <- do.call(rbind, combined_data)
    
    # Adding sample size, response rate and working model scenario number
    combined_data_all_temp$n <- n
    combined_data_all_temp$RR <- rr
    combined_data_all_temp$scenario <- s
    
    # Saving the data
    file_name <- paste0("C:\...\\robust\\combined_robust_results_rr", rr, "_n", n, "_s", s, ".rds")
     saveRDS(combined_data_all_temp, file = file_name)

    
     
}


```




## # PART 1: Calculating the Pooled Parameters for MICE variants

```{r}
sample_sizes <-  c(50, 100, 200, 500, 1000)
response_rates <- c(60, 70,  80)
scenarios <- c(1, 2, 3, 4, 5)

# Looping the result files created in R script "simulation_code_main" for 
# MICE variants
for(s in scenarios){
  for (ss in sample_sizes){
    for (rr in response_rates){
        
        # Path where the result files for the MICE variants are located
        file_name <- paste0("C:\\...\\mice\\results\\simulation_rr", rr, "_n", ss, "_s", s, "_MICE.RData")
        load(file_name)
  
      }
    }
  }

```


```{r}
# Parameter list:
# scenario, response rate, sample size
param_list <- list(
  list(1, 60, 50      ) ,
  list(1, 70, 50      ) ,
  list(1, 80, 50      ) ,
  list(1, 60, 100     ) ,
  list(1, 70, 100     ) ,
  list(1, 80, 100     ) ,
  list(1, 60, 200     ) ,
  list(1, 70, 200     ) ,
  list(1, 80, 200     ) ,
  list(1, 60, 500     ) ,
  list(1, 70, 500     ) ,
  list(1, 80, 500     ) ,
  list(1, 60, 1000    ) ,
  list(1, 70, 1000    ) ,
  list(1, 80, 1000    ) ,
  list(2, 60, 50      ) ,
  list(2, 70, 50      ) ,
  list(2, 80, 50      ) ,
  list(2, 60, 100     ) ,
  list(2, 70, 100     ) ,
  list(2, 80, 100     ) ,
  list(2, 60, 200     ) ,
  list(2, 70, 200     ) ,
  list(2, 80, 200     ) ,
  list(2, 60, 500     ) ,
  list(2, 70, 500     ) ,
  list(2, 80, 500     ) ,
  list(2, 60, 1000    ) ,
  list(2, 70, 1000    ) ,
  list(2, 80, 1000    ) ,
  list(3, 60, 50      ) ,
  list(3, 70, 50      ) ,
  list(3, 80, 50      ) ,
  list(3, 60, 100     ) ,
  list(3, 70, 100     ) ,
  list(3, 80, 100     ) ,
  list(3, 60, 200     ) ,
  list(3, 70, 200     ) ,
  list(3, 80, 200     ) ,
  list(3, 60, 500     ) ,
  list(3, 70, 500     ) ,
  list(3, 80, 500     ) ,
  list(3, 60, 1000    ) ,
  list(3, 70, 1000    ) ,
  list(3, 80, 1000    ) ,
  list(4, 60, 50      ) ,
  list(4, 70, 50      ) ,
  list(4, 80, 50      ) ,
  list(4, 60, 100     ) ,
  list(4, 70, 100     ) ,
  list(4, 80, 100     ) ,
  list(4, 60, 200     ) ,
  list(4, 70, 200     ) ,
  list(4, 80, 200     ) ,
  list(4, 60, 500     ) ,
  list(4, 70, 500     ) ,
  list(4, 80, 500     ) ,
  list(4, 60, 1000    ) ,
  list(4, 70, 1000    ) ,
  list(4, 80, 1000    ) ,
  list(5, 60, 50      ) ,
  list(5, 70, 50      ) ,
  list(5, 80, 50      ) ,
  list(5, 60, 100     ) ,
  list(5, 70, 100     ) ,
  list(5, 80, 100     ) ,
  list(5, 60, 200     ) ,
  list(5, 70, 200     ) ,
  list(5, 80, 200     ) ,
  list(5, 60, 500     ) ,
  list(5, 70, 500     ) ,
  list(5, 80, 500     ) ,
  list(5, 60, 1000    ) ,
  list(5, 70, 1000    ) ,
  list(5, 80, 1000    )
)
```

```{r}
# Names of the loaded result files
result_list <- list(
  simulation_rr60_n50_s1_MICE,
  simulation_rr70_n50_s1_MICE,
  simulation_rr80_n50_s1_MICE,
  simulation_rr60_n100_s1_MICE,
  simulation_rr70_n100_s1_MICE,
  simulation_rr80_n100_s1_MICE,
  simulation_rr60_n200_s1_MICE,
  simulation_rr70_n200_s1_MICE,
  simulation_rr80_n200_s1_MICE,
  simulation_rr60_n500_s1_MICE,
  simulation_rr70_n500_s1_MICE,
  simulation_rr80_n500_s1_MICE,
  simulation_rr60_n1000_s1_MICE,
  simulation_rr70_n1000_s1_MICE,
  simulation_rr80_n1000_s1_MICE,
  simulation_rr60_n50_s2_MICE,
  simulation_rr70_n50_s2_MICE,
  simulation_rr80_n50_s2_MICE,
  simulation_rr60_n100_s2_MICE,
  simulation_rr70_n100_s2_MICE,
  simulation_rr80_n100_s2_MICE,
  simulation_rr60_n200_s2_MICE,
  simulation_rr70_n200_s2_MICE,
  simulation_rr80_n200_s2_MICE,
  simulation_rr60_n500_s2_MICE,
  simulation_rr70_n500_s2_MICE,
  simulation_rr80_n500_s2_MICE,
  simulation_rr60_n1000_s2_MICE,
  simulation_rr70_n1000_s2_MICE,
  simulation_rr80_n1000_s2_MICE,
  simulation_rr60_n50_s3_MICE,
  simulation_rr70_n50_s3_MICE,
  simulation_rr80_n50_s3_MICE,
  simulation_rr60_n100_s3_MICE,
  simulation_rr70_n100_s3_MICE,
  simulation_rr80_n100_s3_MICE,
  simulation_rr60_n200_s3_MICE,
  simulation_rr70_n200_s3_MICE,
  simulation_rr80_n200_s3_MICE,
  simulation_rr60_n500_s3_MICE,
  simulation_rr70_n500_s3_MICE,
  simulation_rr80_n500_s3_MICE,
  simulation_rr60_n1000_s3_MICE,
  simulation_rr70_n1000_s3_MICE,
  simulation_rr80_n1000_s3_MICE,
  simulation_rr60_n50_s4_MICE,
  simulation_rr70_n50_s4_MICE,
  simulation_rr80_n50_s4_MICE,
  simulation_rr60_n100_s4_MICE,
  simulation_rr70_n100_s4_MICE,
  simulation_rr80_n100_s4_MICE,
  simulation_rr60_n200_s4_MICE,
  simulation_rr70_n200_s4_MICE,
  simulation_rr80_n200_s4_MICE,
  simulation_rr60_n500_s4_MICE,
  simulation_rr70_n500_s4_MICE,
  simulation_rr80_n500_s4_MICE,
  simulation_rr60_n1000_s4_MICE,
  simulation_rr70_n1000_s4_MICE,
  simulation_rr80_n1000_s4_MICE,
  simulation_rr60_n50_s5_MICE,
  simulation_rr70_n50_s5_MICE,
  simulation_rr80_n50_s5_MICE,
  simulation_rr60_n100_s5_MICE,
  simulation_rr70_n100_s5_MICE,
  simulation_rr80_n100_s5_MICE,
  simulation_rr60_n200_s5_MICE,
  simulation_rr70_n200_s5_MICE,
  simulation_rr80_n200_s5_MICE,
  simulation_rr60_n500_s5_MICE,
  simulation_rr70_n500_s5_MICE,
  simulation_rr80_n500_s5_MICE,
  simulation_rr60_n1000_s5_MICE,
  simulation_rr70_n1000_s5_MICE,
  simulation_rr80_n1000_s5_MICE
)
```


```{r}
# Looping each MICE result file
for (idx in 1:length(result_list)){
  
  PP_results <- result_list[[idx]]
  s  <- param_list[[idx]][[1]]
  rr <- param_list[[idx]][[2]]
  n  <- param_list[[idx]][[3]]
  
   # List for the results of each category of Y and for all the results
  Yc1_APP_data <- list()
  Yc2_APP_data <- list()
  Yc3_APP_data <- list()
  combined_data <- list()
  
  # looping the results of each MICE variant
  for (i in 1:length(PP_results)){
    
    # binds the results of the same method during different iterations into a
    # same data frame
    binded_data <- do.call(rbind, PP_results[[i]])
  
    # Calculates pooled parameters: MEP, MSE, SD and CR for each category of Y
    Yc1_APP_data[[i]] <- c(colMeans(binded_data[binded_data$var == 1, c(1, 2)]),
                           sd(binded_data[binded_data$var == 1, 1]),
                           mean(binded_data[binded_data$var == 1, 5]))
    names(Yc1_APP_data[[i]]) <- c("Est", "SE", "SD", "CR")
    
    
    Yc2_APP_data[[i]] <- c(colMeans(binded_data[binded_data$var == 2, c(1, 2)]),
                           sd(binded_data[binded_data$var == 2, 1]),
                           mean(binded_data[binded_data$var == 2, 5]))
    
    names(Yc2_APP_data[[i]]) <- c("Est", "SE", "SD", "CR")
    
    Yc3_APP_data[[i]] <- c(colMeans(binded_data[binded_data$var == 3, c(1, 2)]),
                           sd(binded_data[binded_data$var == 3, 1]),
                           mean(binded_data[binded_data$var == 3, 5]))
    
    names(Yc3_APP_data[[i]]) <- c("Est", "SE", "SD", "CR")
    
    combined_data[[i]] <- binded_data
    combined_data[[i]]$method <- i
  
    }

  
    # Combining the results from each list and adding method number and the
    # category level of Y
   # NOTE:
    # 10 = MICE default
    # 11 = MICE CM
    # 12 = MICE INM
    # 13 = MICE INNM
    Yc1_APP_data2 <- as.data.frame(do.call(rbind,Yc1_APP_data))
    Yc1_APP_data2$method <- c(10, 11, 12, 13)
    Yc1_APP_data2$level <- 1 # Category of Y
    
    Yc2_APP_data2 <- as.data.frame(do.call(rbind,Yc2_APP_data))
    Yc2_APP_data2$method <- c(10, 11, 12, 13)
    Yc2_APP_data2$level <- 2
    
    Yc3_APP_data2 <- as.data.frame(do.call(rbind,Yc3_APP_data))
    Yc3_APP_data2$method <- c(10, 11, 12, 13)
    Yc3_APP_data2$level <- 3 
    
    # Combining the pooled results into a same dataframe
    pooled_param_data_all_temp <- do.call(rbind, list(Yc1_APP_data2, Yc2_APP_data2, Yc3_APP_data2))
    pooled_param_data_all_temp$n <- n
    pooled_param_data_all_temp$RR <- rr
    pooled_param_data_all_temp$scenario <- s
    pooled_param_data_all_temp
    
    # Saving the results
    file_name <- paste0("C:\\...\\Pooled results\\pooled_MICE_results_rr", rr, "_n", n, "_s", s, ".rds")
      
    saveRDS(pooled_param_data_all_temp, file = file_name)
    
    # Saving the data from each separate iteration for each method
    combined_data_all_temp <- do.call(rbind, combined_data)
    combined_data_all_temp[combined_data_all_temp$method == 1, 8] <- 10
    combined_data_all_temp[combined_data_all_temp$method == 2, 8] <- 11
    combined_data_all_temp[combined_data_all_temp$method == 3, 8] <- 12
    combined_data_all_temp[combined_data_all_temp$method == 4, 8] <- 13
    
    # Adding sample size, response rate and working model scenario number
    combined_data_all_temp$n <- n
    combined_data_all_temp$RR <- rr
    combined_data_all_temp$scenario <- s
    combined_data_all_temp
    
    # Saving the data
    file_name <- paste0("C:\\...\\Combined result\\mice\\combined_MICE_results_rr", rr, "_n",n, "_s", s, ".rds")
     saveRDS(combined_data_all_temp, file = file_name)
         
}


```


## 1.3 Combining all results

```{r}
# A list to combine the results of the robust methods and MICE variants
all_combined_results_list <- list()

# NOTE: The folder has to include all the combined files created for all the
# methods in each condition combination
combined_files <- list.files(path = "C:\\...\\Combined results",
                                      pattern = ".rds", full.names = T)

# Looping each saved "comdined_data" file
iterno <- 1
for(file in combined_files){
  combined_file <- readRDS(file)

    all_combined_results_list[[iterno]] <- combined_file
    iterno <- iterno + 1

}

```


```{r}
# Combining all the results from the lists
all_combined_results <- do.call(rbind, all_combined_results_list)

# Changing categorical variables into factors
all_combined_results$var <- as.factor(all_combined_results$var)
all_combined_results$method <- as.factor(all_combined_results$method) 
all_combined_results$n <- as.factor(all_combined_results$n)
all_combined_results$RR <- as.factor(all_combined_results$RR)
all_combined_results$scenario <- as.factor(all_combined_results$scenario) 

# Saving the data including the results of all the methods 
save(all_combined_results, file = "all_combined_results.RData")
```


## 1.4 Complete Case Analysis (CCA)

```{r}
# Reading CCA for one specific condition combination
# -> parameters in the path need to be changed to match the right condition

n <- 1000
RR <- 80
s <- 4

# The file includes ASP and SD in columns and rows represent the categories
# of Y
load(paste0("C:\\...\\sample proportions\\simulation_rr", RR, "_n", n, "_s",s, "_CCA.RData"))

# simulation_rr60_n50_s1_CCA
```


## 1.5 (HL) Error Checking

Calculating HL errors during simulation.

```{r}
# Checking the error counts for robust for each condition by opening the
# correct "it inf" file

# NOTE: the the parameters in the path needs to be changed to match the right 
# condition combination
error_count<- readRDS("C://...//robust//it info//simulation_rr80_n1000_s5_robust_it_inf.rds")
round(error_count, 3)


```

```{r}
# Checking the error counts for MICE for each condition by opening the
# correct "it inf" file

# NOTE: the the parameters in the path needs to be changed to match the right 
# condition combination
error_count<- readRDS("C://...//mice//it info//simulation_rr80_n1000_s5_MICE_it_inf.rds")
round(error_count, 3)


```



# PART 2: PLOTS


```{r}
# After all the pooled estimates have been saved, the files are looped to
# combine them for the general figures.  

# List for all the pooled parameters results
all_pooled_results_list <- list()

# File path in which all the pooled parameter files are located
pooled_files <- list.files(path = "C:\\...\\Pooled results",
                           pattern = ".rds", full.names = T)

iterno <- 1

# looping each file
for(file in pooled_files){
  pooled_file <- readRDS(file)

    all_pooled_results_list[[iterno]] <- pooled_file
    iterno <- iterno + 1

}

```


```{r}
# Combining all the pooled results from the list
all_pooled_results <- do.call(rbind, all_pooled_results_list)

# Changing all categorical variables into factors
all_pooled_results$level <- as.factor(all_pooled_results$level)
all_pooled_results$method <- as.factor(all_pooled_results$method) 
all_pooled_results$RR <- as.factor(all_pooled_results$RR)
all_pooled_results$scenario <- as.factor(all_pooled_results$scenario) 

```

```{r}
# Creating a grouping variable for methods: 
# proposed methods are 1, old robust methods 2 and MICE variants 3
all_pooled_results2  <- all_pooled_results
all_pooled_results2$Group <- 0

all_pooled_results2[all_pooled_results2$method == 1, 10] <- 1 
all_pooled_results2[all_pooled_results2$method == 2, 10] <- 1 
all_pooled_results2[all_pooled_results2$method == 3, 10] <- 1 
all_pooled_results2[all_pooled_results2$method == 4, 10] <- 1 
all_pooled_results2[all_pooled_results2$method == 5, 10] <- 1 
all_pooled_results2[all_pooled_results2$method == 6, 10] <- 1 

all_pooled_results2[all_pooled_results2$method == 7, 10] <- 2 
all_pooled_results2[all_pooled_results2$method == 8, 10] <- 2 
all_pooled_results2[all_pooled_results2$method == 9, 10] <- 2 

all_pooled_results2[all_pooled_results2$method == 10, 10] <- 3 
all_pooled_results2[all_pooled_results2$method == 11, 10] <- 3 
all_pooled_results2[all_pooled_results2$method == 12, 10] <- 3 
all_pooled_results2[all_pooled_results2$method == 13, 10] <- 3 

all_pooled_results2$Group <- as.factor(all_pooled_results2$Group)

```


## 2.1. General Plots

```{r}
# Naming the methods for the outputs
method_names <- c(expression(MICE[default]),
                  expression(MICE[CM]),
                  expression(MICE[INM]),
                  expression(MICE[INNM]),
                  expression(MRIC[R[MF]^2]),
                  expression(MRIC[R[CS]^2]),
                  expression(MRIC[R[MZ]^2]),
                  expression(MRIC[R[N]^2]),
                  expression(MRIC[AIC]),
                  expression(MRIC[HL]),
                  expression(MRNNMI),
                  "DRNNMI", 
                  "MRPMMI")

# Assigning the colors for each method
method_colors <- c("#00AFBB", 
                   "#DDCC77", 
                   "#CC6677", 
                   "#AA4499",
                   "purple2", 
                   "orange2",
                   "sienna4",
                   "gray44",
                   "#999933",
                   "darkblue",
                   "#882255",
                   "#117733",
                   "red3")
```




```{r}
# General plot for the category 1 of Y 
df_plot_y1 <- all_pooled_results2[all_pooled_results2$level == 1, ]

df_plot_y1$level <- factor(df_plot_y1$level, 
                      levels = c(1, 2, 3), 
                      labels = c("P(Y = 1) = .10", 
                                 "P(Y = 2) = .38", 
                                 "P(Y = 3) = .52"))

df_plot_y1$RR <- factor(df_plot_y1$RR, 
                      levels = c(60, 70, 80), 
                      labels = c("RR = 60", "RR = 70", "RR = 80"))

df_plot_y1$scenario <- factor(df_plot_y1$scenario, 
                      levels = c(1, 2, 3, 4, 5), 
                      labels = c("Scenario 1", 
                                 "Scenario 2", 
                                 "Scenario 3", 
                                 "Scenario 4", 
                                 "Scenario 5"))

df_plot_y1$Group <- factor(df_plot_y1$Group, 
                      levels = c(1, 2, 3), 
                      labels = c("MRIC Methods",
                                 "Other Robust Methods",
                                 "MICE Variants"))

library(tidyverse)
plot_y1 <- df_plot_y1 %>%
  ggplot(aes(x = n, y = Est))+
  geom_line(aes(color = method, group = method, linetype = 
                  method %in% c("1", "2", "3", "4", "5", "6", "10", "11", 
                                "12", "13"))) +
  scale_linetype_manual(values = c("TRUE" = "solid", "FALSE" = "solid")) +
  geom_point(aes(color=method, shape = method, size = method))+
   scale_shape_manual("MI Methods", 
                      values=c(1, 1, 1, 1, 2, 2, 2, 2, 2, 2,  4, 4, 4),
                      limits = factor(c(10, 11, 12, 13, 1, 2, 3, 4, 5, 6, 7, 
                                        8, 9)),
                      labels = method_names)+
  scale_size_manual("MI Methods", values= c( 1, 1, 1, 1, 1.5, 1.5, 1.5, 1.5, 
                                             1.5, 1.5, 1.5, 1.5, 1.5),
                    limits = factor(c(10, 11, 12, 13, 1, 2, 3, 4, 5, 6, 7, 
                                      8, 9)),
                    labels = method_names)+
  guides(linetype = "none") +
  theme_classic()+
  facet_grid(RR~scenario) + 
  theme(legend.text.align = 0) +
  xlab("n") +
  ylab("AEP") +
  ggtitle("") +
    scale_colour_manual(name="MI Methods",
                        values = method_colors,
                        limits = factor(c(10, 11, 12, 13, 1, 2, 3, 4, 5, 6, 7, 
                                          8, 9)),
                        labels = method_names) +
  xlim(0, 1050) + 
  ylim(0.07, 0.18)

hline_data <- data.frame(var = 1,
                          hline = 0.10)

hline_data$var <- factor(hline_data$var)
levels(hline_data$var) <- c("P(Y = 1) = .10")


  
plot_y1_final <- plot_y1 +
  geom_hline(data = hline_data, aes(yintercept = hline), linetype = "dashed",
             size = 0.3)

plot_y1_final

# Path where the figure is saved
file_name <- paste0("C:\\...\\Plots\\plot_y1.pdf")
ggsave(plot_y1_final, height = 5, width = 8, filename = file_name, dpi = 300)
```



```{r}
# General plot for category 2 of Y
df_plot_y2 <- all_pooled_results2[all_pooled_results2$level == 2, ]

df_plot_y2$level <- factor(df_plot_y2$level, 
                      levels = c(1, 2, 3), 
                      labels = c("P(Y = 1) = .10", 
                                 "P(Y = 2) = .38", 
                                 "P(Y = 3) = .52"))

df_plot_y2$RR <- factor(df_plot_y2$RR, 
                      levels = c(60, 70, 80), 
                      labels = c("RR = 60", "RR = 70", "RR = 80"))

df_plot_y2$scenario <- factor(df_plot_y2$scenario, 
                      levels = c(1, 2, 3, 4, 5), 
                      labels = c("Scenario 1", 
                                 "Scenario 2", 
                                 "Scenario 3", 
                                 "Scenario 4", 
                                 "Scenario 5"))

library(tidyverse)
plot_y2 <- df_plot_y2 %>%
  ggplot(aes(x = n, y = Est))+
  geom_line(aes(color = method, group = method, linetype = 
                  method %in% c("1", "2", "3", "4", "5", "6", "10", "11", 
                                "12", "13"))) +
  scale_linetype_manual(values = c("TRUE" = "solid", "FALSE" = "solid")) +
  geom_point(aes(color=method, shape = method, size = method))+
  scale_shape_manual("MI Methods", values=c(1, 1, 1, 1, 2, 2, 2, 2, 2, 2,  4, 
                                             4, 4),
                      limits = factor(c(10, 11, 12, 13, 1, 2, 3, 4, 5, 6, 7, 
                                        8, 9)),
                      labels = method_names)+
  scale_size_manual("MI Methods", values=c( 1, 1, 1, 1, 1.5, 1.5, 1.5, 1.5, 
                                            1.5, 1.5, 1.5, 1.5, 1.5),
                    limits = factor(c(10, 11, 12, 13, 1, 2, 3, 4, 5, 6, 7, 
                                      8, 9)),
                    labels = method_names)+
  guides(linetype = "none") +
  theme_classic() +
  facet_grid(RR~scenario) + 
  theme(legend.text.align = 0) +
  xlab("n") +
  ylab("AEP") +
  ggtitle("") +
    scale_colour_manual(name="MI Methods",
                        values = method_colors,
                        limits = factor(c(10, 11, 12, 13, 1, 2, 3, 4, 5, 6, 7, 
                                          8, 9)),
                        labels = method_names) +
  xlim(0, 1050) +
  ylim(0.35, 0.48)

hline_data <- data.frame(var = 1,
                          hline = 0.38)

hline_data$var <- factor(hline_data$var)
levels(hline_data$var) <- c("P(Y = 2) = .38")


  
plot_y2_final <- plot_y2 +
  geom_hline(data = hline_data, aes(yintercept = hline), linetype = "dashed",
             size = 0.3)

plot_y2_final

# Path where the figure is saved
file_name <- paste0("C:\\...\\Plots\\plot_y2.pdf")
ggsave(plot_y2_final, height = 5, width = 8, filename = file_name, dpi = 300)
```



```{r}
# General plot for category 3 of Y
df_plot_y3 <- all_pooled_results2[all_pooled_results2$level == 3, ]

df_plot_y3$level <- factor(df_plot_y3$level, 
                      levels = c(1, 2, 3), 
                      labels = c("P(Y = 1) = .10", 
                                 "P(Y = 2) = .38", 
                                 "P(Y = 3) = .52"))

df_plot_y3$RR <- factor(df_plot_y3$RR, 
                      levels = c(60, 70, 80), 
                      labels = c("RR = 60", "RR = 70", "RR = 80"))

df_plot_y3$scenario <- factor(df_plot_y3$scenario, 
                      levels = c(1, 2, 3, 4, 5), 
                      labels = c("Scenario 1", 
                                 "Scenario 2", 
                                 "Scenario 3", 
                                 "Scenario 4", 
                                 "Scenario 5"))

library(tidyverse)
plot_y3 <- df_plot_y3 %>%
  ggplot(aes(x = n, y = Est))+
  geom_line(aes(color = method, group = method, linetype = 
                  method %in% c("1", "2", "3", "4", "5", "6", "10", "11", 
                                "12", "13"))) +
  scale_linetype_manual(values = c("TRUE" = "solid", "FALSE" = "solid")) +
  geom_point(aes(color=method, shape = method, size = method))+
   scale_shape_manual("MI Methods", values=c(1, 1, 1, 1, 2, 2, 2, 2, 2, 2,  4, 
                                             4, 4),
                      limits = factor(c(10, 11, 12, 13, 1, 2, 3, 4, 5, 6, 7, 
                                        8, 9)),
                      labels = method_names)+
  scale_size_manual("MI Methods", values=c( 1, 1, 1, 1, 1.5, 1.5, 1.5, 1.5, 
                                            1.5, 1.5, 1.5, 1.5, 1.5),
                    limits = factor(c(10, 11, 12, 13, 1, 2, 3, 4, 5, 6, 7, 
                                      8, 9)),
                    labels = method_names)+
  guides(linetype = "none") +
  theme_classic() +
  facet_grid(RR~scenario) + 
  theme(legend.text.align = 0) +
  xlab("n") +
  ylab("AEP") +
  ggtitle("") +
    scale_colour_manual(name="MI Methods",
                        values = method_colors,
                        limits = factor(c(10, 11, 12, 13, 1, 2, 3, 4, 5, 6, 7, 8, 9)),
                        labels = method_names) +
  xlim(0, 1050) +
  ylim(0.4, 0.55)

hline_data <- data.frame(var = 1,
                          hline = 0.52)

hline_data$var <- factor(hline_data$var)
levels(hline_data$var) <- c("P(Y = 3) = .52")


  
plot_y3_final <- plot_y3 +
  geom_hline(data = hline_data, aes(yintercept = hline), linetype = "dashed",
             size = 0.3)

plot_y3_final

# Path where the figure is saved
file_name <- paste0("C:\\...\\Plots\\plot_y3.pdf")
ggsave(plot_y3_final, height = 5, width = 8, filename = file_name, dpi = 300)
```



## 2.2 Plots for Appendix D


```{r}
method_names <- c(expression(MRIC[R[MF]^2]),
                  expression(MRIC[R[CS]^2]),
                  expression(MRIC[R[MZ]^2]),
                  expression(MRIC[R[N]^2]),
                  expression(MRIC[AIC]),
                  expression(MRIC[HL]),
                  expression(MRNNMI),
                  "DRNNMI", 
                  "MRPMMI")

method_colors <- c("purple2", 
                    "orange2",
                   "sienna4",
                   "gray44",
                   "#999933",
                   "darkblue",
                   "#882255",
                   "#117733",
                   "red3")
```


```{r}
df_plot_s2_y1 <- all_pooled_results2[all_pooled_results2$level == 1 &
                                    all_pooled_results2$scenario == 2 &
                                   all_pooled_results2$method == c(1, 2, 3, 4, 
                                                                   5, 6, 7, 8, 
                                                                   9),  ]

df_plot_s2_y1$level <- factor(df_plot_s2_y1$level, 
                      levels = c(1, 2, 3), 
                      labels = c("P(Y = 1) = .10", 
                                 "P(Y = 2) = .38", 
                                 "P(Y = 3) = .52"))

df_plot_s2_y1$RR <- factor(df_plot_s2_y1$RR, 
                      levels = c(60, 70, 80), 
                      labels = c("RR = 60", "RR = 70", "RR = 80"))

df_plot_s2_y1$scenario <- factor(df_plot_s2_y1$scenario, 
                      levels = c(1, 2, 3, 4, 5), 
                      labels = c("Scenario 1", 
                                 "Scenario 2", 
                                 "Scenario 3", 
                                 "Scenario 4", 
                                 "Scenario 5"))


library(tidyverse)
plot_s2_y1 <- df_plot_s2_y1 %>%
  ggplot(aes(x = n, y = Est))+
  geom_line(aes(color = method, group = method, linetype = 
                  method %in% c("1", "2", "3", "4", "5", "6", "10", "11", 
                                "12", "13"))) +
  scale_linetype_manual(values = c("TRUE" = "solid", "FALSE" = "solid")) +
  geom_point(aes(color=method, shape = method, size = method))+
   scale_shape_manual("MI Methods", values=c(2, 2, 2, 2, 2, 2,  4, 4, 4),
                      limits = factor(c(1, 2, 3, 4, 5, 6, 7, 8, 9)),
                      labels = method_names)+
  scale_size_manual("MI Methods", values=c( 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
                                     1.5, 1.5, 1.5),
                    limits = factor(c(1, 2, 3, 4, 5, 6, 7, 8, 9)),
                    labels = method_names)+
  guides(linetype = "none") +
  theme_classic()+
  facet_grid(RR~scenario) + 
  theme(legend.text.align = 0) +
  xlab("n") +
  ylab("AEP") +
  ggtitle("") +
    scale_colour_manual(name="MI Methods",
                        values = method_colors,
                        limits = factor(c(1, 2, 3, 4, 5, 6, 7, 8, 9)),
                        labels = method_names) +
  xlim(0, 1050) 


hline_data <- data.frame(var = 1,
                          hline = 0.10)

hline_data$var <- factor(hline_data$var)
levels(hline_data$var) <- c("P(Y = 1) = .10")


  
plot_s2_y1_final <- plot_s2_y1 +
  geom_hline(data = hline_data, aes(yintercept = hline), linetype = "dashed",
             size = 0.3)

plot_s2_y1_final

# Path where the figure is saved
file_name <- paste0("C:\\...\\Plots\\plot_s2_y1.pdf")
ggsave(plot_s2_y1_final, height = 5, width = 8, filename = file_name, dpi = 300)
```


```{r}
df_plot_s2_y2 <- all_pooled_results2[all_pooled_results2$level == 2 &
                                    all_pooled_results2$scenario == 2 &
                                   all_pooled_results2$method == c(1, 2, 3, 4, 
                                                                   5, 6, 7, 8, 
                                                                   9),  ]

df_plot_s2_y2$level <- factor(df_plot_s2_y2$level, 
                      levels = c(1, 2, 3), 
                      labels = c("P(Y = 1) = .10", 
                                 "P(Y = 2) = .38", 
                                 "P(Y = 3) = .52"))

df_plot_s2_y2$RR <- factor(df_plot_s2_y2$RR, 
                      levels = c(60, 70, 80), 
                      labels = c("RR = 60", "RR = 70", "RR = 80"))

df_plot_s2_y2$scenario <- factor(df_plot_s2_y2$scenario, 
                      levels = c(1, 2, 3, 4, 5), 
                      labels = c("Scenario 1", 
                                 "Scenario 2", 
                                 "Scenario 3", 
                                 "Scenario 4", 
                                 "Scenario 5"))


library(tidyverse)
plot_s2_y2 <- df_plot_s2_y2 %>%
  ggplot(aes(x = n, y = Est))+
  geom_line(aes(color = method, group = method, linetype = 
                  method %in% c("1", "2", "3", "4", "5", "6", "10", "11", 
                                "12", "13"))) +
  scale_linetype_manual(values = c("TRUE" = "solid", "FALSE" = "solid")) +
  geom_point(aes(color=method, shape = method, size = method))+
   scale_shape_manual("MI Methods", values=c(2, 2, 2, 2, 2, 2,  4, 4, 4),
                      limits = factor(c(1, 2, 3, 4, 5, 6, 7, 8, 9)),
                      labels = method_names)+
  scale_size_manual("MI Methods", values=c( 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
                                     1.5, 1.5, 1.5),
                    limits = factor(c(1, 2, 3, 4, 5, 6, 7, 8, 9)),
                    labels = method_names)+
  guides(linetype = "none") +
  theme_classic()+
  facet_grid(RR~scenario) + 
  theme(legend.text.align = 0) +
  xlab("n") +
  ylab("AEP") +
  ggtitle("") +
    scale_colour_manual(name="MI Methods",
                        values = method_colors,
                        limits = factor(c(1, 2, 3, 4, 5, 6, 7, 8, 9)),
                        labels = method_names) +
  xlim(0, 1050)



hline_data <- data.frame(var = 1,
                          hline = 0.38)

hline_data$var <- factor(hline_data$var)
levels(hline_data$var) <- c("P(Y = 1) = .38")


  
plot_s2_y2_final <- plot_s2_y2 +
  geom_hline(data = hline_data, aes(yintercept = hline), linetype = "dashed",
             size = 0.3)

plot_s2_y2_final

# Path where the figure is saved
file_name <- paste0("C:\\...\\Plots\\plot_s2_y2.pdf")
ggsave(plot_s2_y2_final, height = 5, width = 8, filename = file_name, dpi = 300)
```

```{r}
df_plot_s2_y3 <- all_pooled_results2[all_pooled_results2$level == 3 &
                                       all_pooled_results2$scenario == 2 &
                                      all_pooled_results2$method == c(1, 2, 3, 4, 
                                                                   5, 6, 7, 8, 
                                                                   9),  ]

df_plot_s2_y3$level <- factor(df_plot_s2_y3$level, 
                      levels = c(1, 2, 3), 
                      labels = c("P(Y = 1) = .10", 
                                 "P(Y = 2) = .38", 
                                 "P(Y = 3) = .52"))

df_plot_s2_y3$RR <- factor(df_plot_s2_y3$RR, 
                      levels = c(60, 70, 80), 
                      labels = c("RR = 60", "RR = 70", "RR = 80"))

df_plot_s2_y3$scenario <- factor(df_plot_s2_y3$scenario, 
                      levels = c(1, 2, 3, 4, 5), 
                      labels = c("Scenario 1", 
                                 "Scenario 2", 
                                 "Scenario 3", 
                                 "Scenario 4", 
                                 "Scenario 5"))


library(tidyverse)
plot_s2_y3 <- df_plot_s2_y3 %>%
  ggplot(aes(x = n, y = Est))+
  geom_line(aes(color = method, group = method, linetype = 
                  method %in% c("1", "2", "3", "4", "5", "6", "10", "11", 
                                "12", "13"))) +
  scale_linetype_manual(values = c("TRUE" = "solid", "FALSE" = "solid")) +
  geom_point(aes(color=method, shape = method, size = method))+
   scale_shape_manual("MI Methods", values=c(2, 2, 2, 2, 2, 2,  4, 4, 4),
                      limits = factor(c(1, 2, 3, 4, 5, 6, 7, 8, 9)),
                      labels = method_names)+
  scale_size_manual("MI Methods", values=c( 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
                                     1.5, 1.5, 1.5),
                    limits = factor(c(1, 2, 3, 4, 5, 6, 7, 8, 9)),
                    labels = method_names)+
  guides(linetype = "none") +
  theme_classic()+
  facet_grid(RR~scenario) + 
  theme(legend.text.align = 0) +
  xlab("n") +
  ylab("AEP") +
  ggtitle("") +
    scale_colour_manual(name="MI Methods",
                        values = method_colors,
                        limits = factor(c(1, 2, 3, 4, 5, 6, 7, 8, 9)),
                        labels = method_names) +
  xlim(0, 1050)


hline_data <- data.frame(var = 1,
                          hline = 0.52)

hline_data$var <- factor(hline_data$var)
levels(hline_data$var) <- c("P(Y = 1) = .52")


  
plot_s2_y3_final <- plot_s2_y3 +
  geom_hline(data = hline_data, aes(yintercept = hline), linetype = "dashed",
             size = 0.3)

plot_s2_y3_final

# Path where the figure is saved
file_name <- paste0("C:\\...\\Plots\\plot_s2_y3.pdf")
ggsave(plot_s2_y3_final, height = 5, width = 8, filename = file_name, dpi = 300)
```



## 2.3 Plots for Scenario 2 

```{r}
# Load the file including the combined results for the 5000 iterations
file_name <- paste0("C:...\all_combined_results.RData")
load(file_name)
```


### Plots for n = 50

```{r}
# Plot when n = 50 and RR = 60
df_plot2_RR60_n50_s2 <- all_combined_results[all_combined_results$n == 50 &
                                          all_combined_results$RR == 60 &
                                            all_combined_results$scenario == 2,]


df_plot2_RR60_n50_s2$RR <- factor(df_plot2_RR60_n50_s2$RR, 
                      levels = c(60, 70, 80), 
                      labels = c("RR = 60", "RR = 70", "RR = 80"))

df_plot2_RR60_n50_s2$var <- factor(df_plot2_RR60_n50_s2$var, 
                      levels = c(1, 2, 3), 
                      labels = c("P(Y = 1) = .10", "P(Y = 2) = .38", "P(Y = 3) = .52"))

df_plot2_RR60_n50_s2$n <- factor(df_plot2_RR60_n50_s2$n, 
                      levels = c(50, 100, 200, 500), 
                      labels = c("n = 50", "n = 100", "n = 200", "n = 500"))


library(dplyr)
library(ggplot2)


plot2_RR60_n50_s2  <- df_plot2_RR60_n50_s2  %>%
  ggplot(aes(x = method, y = Est, fill = var)) + 
  geom_boxplot(alpha = .5) + 
  theme_classic() +
  coord_flip() +
    scale_x_discrete(labels = c(expression(MRIC[R[MF]^2]),
                                expression(MRIC[R[CS]^2]),
                                expression(MRIC[R[MZ]^2]),
                                expression(MRIC[R[N]^2]),
                                expression(MRIC[AIC]),
                                expression(MRIC[HL]),
                                expression(MRNNMI),
                                "DRNNMI", 
                                "MRPMMI",
                                expression(MICE[default]),
                                expression(MICE[CM]),
                                expression(MICE[INM]),
                                expression(MICE[INNM]))) +
 theme(axis.text.y = element_text(hjust = 0)) +
  xlab("") +
  ylab("EP") + 
  labs(fill = "Y Category") +
  theme(legend.position='top')
  

hline_data <- data.frame(var = unique(df_plot2_RR60_n50_s2$var),
                          hline = c(0.10036, 0.37615, 0.52349))



plot2_RR60_n50_s2_final <- plot2_RR60_n50_s2 +
  geom_hline(data = hline_data, aes(yintercept = hline), linetype = "dashed")

plot2_RR60_n50_s2_final

# Path where the figure is saved
file_name <- paste0("C:\\...\\Plots\\plot2_RR60_n50_s2.pdf")
ggsave(plot2_RR60_n50_s2_final, height = 6, width = 6, filename = file_name, dpi = 300)
```


```{r}
# Plot when n = 50 and RR = 70
df_plot2_RR70_n50_s2 <- all_combined_results[all_combined_results$n == 50 &
                                          all_combined_results$RR == 70 &
                                            all_combined_results$scenario == 2,]


df_plot2_RR70_n50_s2$RR <- factor(df_plot2_RR70_n50_s2$RR, 
                      levels = c(60, 70, 80), 
                      labels = c("RR = 60", "RR = 70", "RR = 80"))

df_plot2_RR70_n50_s2$var <- factor(df_plot2_RR70_n50_s2$var, 
                      levels = c(1, 2, 3), 
                      labels = c("P(Y = 1) = .10", "P(Y = 2) = .38", "P(Y = 3) = .52"))

df_plot2_RR70_n50_s2$n <- factor(df_plot2_RR70_n50_s2$n, 
                      levels = c(50, 100, 200, 500), 
                      labels = c("n = 50", "n = 100", "n = 200", "n = 500"))


library(dplyr)
library(ggplot2)

plot2_RR70_n50_s2  <- df_plot2_RR70_n50_s2  %>%
  ggplot(aes(x = method, y = Est, fill = var)) + 
  geom_boxplot(alpha = .5) + 
  theme_classic() +
  coord_flip() +
    scale_x_discrete(labels = c(expression(MRIC[R[MF]^2]),
                                expression(MRIC[R[CS]^2]),
                                expression(MRIC[R[MZ]^2]),
                                expression(MRIC[R[N]^2]),
                                expression(MRIC[AIC]),
                                expression(MRIC[HL]),
                                expression(MRNNMI),
                                "DRNNMI", 
                                "MRPMMI",
                                expression(MICE[default]),
                                expression(MICE[CM]),
                                expression(MICE[INM]),
                                expression(MICE[INNM]))) +
 theme(axis.text.y = element_text(hjust = 0)) +
  xlab("") +
  ylab("EP") + 
  labs(fill = "Y Category") +
    theme(legend.position='top')
  

hline_data <- data.frame(var = unique(df_plot2_RR70_n50_s2$var),
                          hline = c(0.10036, 0.37615, 0.52349))



plot2_RR70_n50_s2_final <- plot2_RR70_n50_s2 +
  geom_hline(data = hline_data, aes(yintercept = hline), linetype = "dashed")

plot2_RR70_n50_s2_final

# Path where the figure is saved
file_name <- paste0("C:\\...\\Plots\\plot2_RR70_n50_s2.pdf")
ggsave(plot2_RR70_n50_s2_final, height = 6, width = 6, filename = file_name, dpi = 300)
```



```{r}
# Plot when n = 50 and RR = 80
df_plot2_RR80_n50_s2 <- all_combined_results[all_combined_results$n == 50 &
                                          all_combined_results$RR == 80 &
                                            all_combined_results$scenario == 2,]


df_plot2_RR80_n50_s2$RR <- factor(df_plot2_RR80_n50_s2$RR, 
                      levels = c(60, 70, 80), 
                      labels = c("RR = 60", "RR = 70", "RR = 80"))

df_plot2_RR80_n50_s2$var <- factor(df_plot2_RR80_n50_s2$var, 
                      levels = c(1, 2, 3), 
                      labels = c("P(Y = 1) = .10", "P(Y = 2) = .38", "P(Y = 3) = .52"))

df_plot2_RR80_n50_s2$n <- factor(df_plot2_RR80_n50_s2$n, 
                      levels = c(50, 100, 200, 500), 
                      labels = c("n = 50", "n = 100", "n = 200", "n = 500"))


library(dplyr)
library(ggplot2)
#png(file="robust_methods_plot.jpeg")


plot2_RR80_n50_s2  <- df_plot2_RR80_n50_s2  %>%
  ggplot(aes(x = method, y = Est, fill = var)) + 
  geom_boxplot(alpha = .5) + 
  theme_classic() +
  coord_flip() +
  scale_x_discrete(labels = c(expression(MRIC[R[MF]^2]),
                                expression(MRIC[R[CS]^2]),
                                expression(MRIC[R[MZ]^2]),
                                expression(MRIC[R[N]^2]),
                                expression(MRIC[AIC]),
                                expression(MRIC[HL]),
                                expression(MRNNMI),
                                "DRNNMI", 
                                "MRPMMI",
                                expression(MICE[default]),
                                expression(MICE[CM]),
                                expression(MICE[INM]),
                                expression(MICE[INNM]))) +
 theme(axis.text.y = element_text(hjust = 0)) +
  xlab("") +
  ylab("EP") + 
  labs(fill = "Y Category") +
    theme(legend.position='top')
  

hline_data <- data.frame(var = unique(df_plot2_RR80_n50_s2$var),
                          hline = c(0.10036, 0.37615, 0.52349))



plot2_RR80_n50_s2_final <- plot2_RR80_n50_s2 +
  geom_hline(data = hline_data, aes(yintercept = hline), linetype = "dashed")

plot2_RR80_n50_s2_final

# Path where the figure is saved
file_name <- paste0("C:\\...\\Plots\\plot2_RR80_n50_s2.pdf")
ggsave(plot2_RR80_n50_s2_final, height = 6, width = 6, filename = file_name, dpi = 300)
```


### Plots for n = 500

```{r}
# Plot when n = 500 and RR = 60
df_plot2_RR60_n500_s2 <- all_combined_results[all_combined_results$n == 500 &
                                          all_combined_results$RR == 60 &
                                          all_combined_results$scenario == 2,]


df_plot2_RR60_n500_s2$RR <- factor(df_plot2_RR60_n500_s2$RR, 
                      levels = c(60, 70, 80), 
                      labels = c("RR = 60", "RR = 70", "RR = 80"))

df_plot2_RR60_n500_s2$var <- factor(df_plot2_RR60_n500_s2$var, 
                      levels = c(1, 2, 3), 
                      labels = c("P(Y = 1) = .10", "P(Y = 2) = .38", "P(Y = 3) = .52"))

df_plot2_RR60_n500_s2$n <- factor(df_plot2_RR60_n500_s2$n, 
                      levels = c(50, 100, 200, 500), 
                      labels = c("n = 50", "n = 100", "n = 200", "n = 500"))


library(dplyr)
library(ggplot2)

plot2_RR60_n500_s2  <- df_plot2_RR60_n500_s2  %>%
  ggplot(aes(x = method, y = Est, fill = var)) + 
  geom_boxplot(alpha = .5) + 
  theme_classic() +
  coord_flip() +
    scale_x_discrete(labels = c(expression(MRIC[R[MF]^2]),
                                expression(MRIC[R[CS]^2]),
                                expression(MRIC[R[MZ]^2]),
                                expression(MRIC[R[N]^2]),
                                expression(MRIC[AIC]),
                                expression(MRIC[HL]),
                                expression(MRNNMI),
                                "DRNNMI", 
                                "MRPMMI",
                                expression(MICE[default]),
                                expression(MICE[CM]),
                                expression(MICE[INM]),
                                expression(MICE[INNM]))) +
 theme(axis.text.y = element_text(hjust = 0)) +
  xlab("") +
  ylab("EP") + 
  labs(fill = "Y Category") +
  theme(legend.position='top')
  

hline_data <- data.frame(var = unique(df_plot2_RR60_n500_s2$var),
                          hline = c(0.10036, 0.37615, 0.52349))



plot2_RR60_n500_s2_final <- plot2_RR60_n500_s2 +
  geom_hline(data = hline_data, aes(yintercept = hline), linetype = "dashed")

plot2_RR60_n500_s2_final

# Path where the figure is saved
file_name <- paste0("C:\\...\\Plots\\plot2_RR60_n500_s2.pdf")
ggsave(plot2_RR60_n500_s2_final, height = 6, width = 6, filename = file_name, dpi = 300)
```


```{r}
# Plot when n = 500 and RR = 70
df_plot2_RR70_n500_s2 <- all_combined_results[all_combined_results$n == 500 &
                                          all_combined_results$RR == 70 & 
                                            all_combined_results$scenario == 2,]


df_plot2_RR70_n500_s2$RR <- factor(df_plot2_RR70_n500_s2$RR, 
                      levels = c(60, 70, 80), 
                      labels = c("RR = 60", "RR = 70", "RR = 80"))

df_plot2_RR70_n500_s2$var <- factor(df_plot2_RR70_n500_s2$var, 
                      levels = c(1, 2, 3), 
                      labels = c("P(Y = 1) = .10", "P(Y = 2) = .38", "P(Y = 3) = .52"))

df_plot2_RR70_n500_s2$n <- factor(df_plot2_RR70_n500_s2$n, 
                      levels = c(50, 100, 200, 500), 
                      labels = c("n = 50", "n = 100", "n = 200", "n = 500"))


library(dplyr)
library(ggplot2)

plot2_RR70_n500_s2  <- df_plot2_RR70_n500_s2  %>%
  ggplot(aes(x = method, y = Est, fill = var)) + 
  geom_boxplot(alpha = .5) + 
  theme_classic() +
  coord_flip() +
    scale_x_discrete(labels = c(expression(MRIC[R[MF]^2]),
                                expression(MRIC[R[CS]^2]),
                                expression(MRIC[R[MZ]^2]),
                                expression(MRIC[R[N]^2]),
                                expression(MRIC[AIC]),
                                expression(MRIC[HL]),
                                expression(MRNNMI),
                                "DRNNMI", 
                                "MRPMMI",
                                expression(MICE[default]),
                                expression(MICE[CM]),
                                expression(MICE[INM]),
                                expression(MICE[INNM]))) +
 theme(axis.text.y = element_text(hjust = 0)) +
  xlab("") +
  ylab("EP") + 
  labs(fill = "Y Category") +
    theme(legend.position='top')
  

hline_data <- data.frame(var = unique(df_plot2_RR70_n500_s2$var),
                          hline = c(0.10036, 0.37615, 0.52349))



plot2_RR70_n500_s2_final <- plot2_RR70_n500_s2 +
  geom_hline(data = hline_data, aes(yintercept = hline), linetype = "dashed")

plot2_RR70_n500_s2_final

# Path where the figure is saved
file_name <- paste0("C:\\...\\Plots\\plot2_RR70_n500_s2.pdf")
ggsave(plot2_RR70_n500_s2_final, height = 6, width = 6, filename = file_name, dpi = 300)
```



```{r}
# Plot when n = 500 and RR = 80
df_plot2_RR80_n500_s2 <- all_combined_results[all_combined_results$n == 500 &
                                          all_combined_results$RR == 80 &
                                            all_combined_results$scenario == 2,]


df_plot2_RR80_n500_s2$RR <- factor(df_plot2_RR80_n500_s2$RR, 
                      levels = c(60, 70, 80), 
                      labels = c("RR = 60", "RR = 70", "RR = 80"))

df_plot2_RR80_n500_s2$var <- factor(df_plot2_RR80_n500_s2$var, 
                      levels = c(1, 2, 3), 
                      labels = c("P(Y = 1) = .10", "P(Y = 2) = .38", "P(Y = 3) = .52"))

df_plot2_RR80_n500_s2$n <- factor(df_plot2_RR80_n500_s2$n, 
                      levels = c(50, 100, 200, 500), 
                      labels = c("n = 50", "n = 100", "n = 200", "n = 500"))


library(dplyr)
library(ggplot2)

plot2_RR80_n500_s2  <- df_plot2_RR80_n500_s2  %>%
  ggplot(aes(x = method, y = Est, fill = var)) + 
  geom_boxplot(alpha = .5) + 
  theme_classic() +
  coord_flip() +
    scale_x_discrete(labels = c(expression(MRIC[R[MF]^2]),
                                expression(MRIC[R[CS]^2]),
                                expression(MRIC[R[MZ]^2]),
                                expression(MRIC[R[N]^2]),
                                expression(MRIC[AIC]),
                                expression(MRIC[HL]),
                                expression(MRNNMI),
                                "DRNNMI", 
                                "MRPMMI",
                                expression(MICE[default]),
                                expression(MICE[CM]),
                                expression(MICE[INM]),
                                expression(MICE[INNM]))) +
 theme(axis.text.y = element_text(hjust = 0)) +
  xlab("") +
  ylab("EP") + 
  labs(fill = "Y Category") +
    theme(legend.position='top')
  

hline_data <- data.frame(var = unique(df_plot2_RR80_n500_s2$var),
                          hline = c(0.10036, 0.37615, 0.52349))



plot2_RR80_n500_s2_final <- plot2_RR80_n500_s2 +
  geom_hline(data = hline_data, aes(yintercept = hline), linetype = "dashed")

plot2_RR80_n500_s2_final

# Path where the figure is saved
file_name <- paste0("C:\\...\\Plots\\plot2_RR80_n500_s2.pdf")
ggsave(plot2_RR80_n500_s2_final, height = 6, width = 6, filename = file_name, dpi = 300)
```

